{% set version = "4.5.0" %}

package:
  name: libnetcdf
  version: {{ version }}

source:
  git_url: https://github.com/Unidata/netcdf-c
  git_tag: v4.5.0
  sha256: f7d1cb2a82100b9bf9a1130a50bc5c7baf0de5b5022860ac3e09a0a32f83cf4a
  patches:
    # https://github.com/Unidata/netcdf-c/pull/512
    - 0001-Force-attribute-value-to-be-in-range-vs-causing-erro.patch
    # https://github.com/Unidata/netcdf-c/pull/573
    - 0002-Fix-https-github.com-Unidata-netcdf-c-issues-569.patch
    # https://github.com/Unidata/netcdf-c/pull/729
    - 0003-Fix-buffer-overrun-in-tabs-MAX_NESTS-by-adding-space.patch
    - 0004-Add-find_package-Threads-REQUIRED-to-CMakeLists.txt.patch
    - 0005-Use-refactored-variable-names-introduced-by-773fe807.patch
    - 0006-Fix-build-on-pre-C99-compilers.patch
    - 0007-Add-workaround-for-sscanf-NaN.patch
    - 0008-Make-ncdump_tst_h_rdc0-test-conditional.patch
    - 0009-Prefer-getenv-TOPSRCDIR-over-STRINGIFY-TOPSRCDIR.patch

build:
  number: 7
  run_exports:
    # C has good backcompat, C++ has poor.  Since we only build C, go with good
    #   https://abi-laboratory.pro/tracker/timeline/netcdf/
    #   https://abi-laboratory.pro/tracker/timeline/netcdf-cxx/
    - {{ pin_subpackage('libnetcdf') }}

requirements:
  build:
    - cmake
    - make  # [unix]
    - pkg-config  # [not win]
    - {{ compiler('c') }}
    # not sure if we need cxx compiler here - seems to be presently disabled.
    # - {{ compiler('cxx') }}
    # not sure if we need fortran compiler here - seems to be presently disabled.
    # - {{ compiler('fortran') }}
  host:
    - msinttypes  # [win and vc<14]
    - bzip2
    - curl
    - zlib
    - hdf4
    - hdf5
    - jpeg
  run:
    - curl

test:
  commands:
    - nc-config --all  # [not win]
    - test -f ${PREFIX}/lib/libnetcdf.a  # [not win]
    - test -f ${PREFIX}/lib/libnetcdf.so  # [linux]
    - test -f ${PREFIX}/lib/libnetcdf.dylib  # [osx]
    # Has started to return code 400 (Unrecognized request)
    # - ncdump -h "http://geoport-dev.whoi.edu/thredds/dodsC/estofs/atlantic"
    # - ncdump -h "https://data.nodc.noaa.gov/thredds/dodsC/ioos/sccoos/scripps_pier/scripps_pier-2016.nc"
    - ncdump -h "http://oos.soest.hawaii.edu/thredds/dodsC/hioos/model/atm/ncep_pac/NCEP_Pacific_Atmospheric_Model_best.ncd"
    - ncdump -h "http://oos.soest.hawaii.edu/thredds/dodsC/usgs_dem_10m_tinian"
    - ncdump -h "https://www.ncei.noaa.gov/thredds/dodsC/namanl/201609/20160929/namanl_218_20160929_1800_006.grb"
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://www.unidata.ucar.edu/software/netcdf/
  license: MIT
  license_file: COPYRIGHT
  summary: 'Libraries and data formats that support array-oriented scientific data.'

extra:
  recipe-maintainers:
    - groutr
    - kmuehlbauer
    - ocefpaf
    - mingwandroid
    - msarahan
