{% set version = "4.7.0" %}

package:
  name: libnetcdf
  version: {{ version }}

source:
  url: https://github.com/Unidata/netcdf-c/archive/v{{ version }}.tar.gz
  sha256: 26d03164074363b3911ed79b7cddd045c22adf5ebaf978943db11a1d9f15e9d3
  patches:
    - patches/0003-Add-find_package-Threads-REQUIRED-to-CMakeLists.txt.patch
    - patches/0004-Prefer-getenv-TOPSRCDIR-over-STRINGIFY-TOPSRCDIR.patch
    - patches/0006-Fix-tests-for-Windows-VS2008-define-__func__-as-__FU.patch
    - patches/0008-Finish-the-missing-code-to-handle-VS-in-test_common..patch
    - patches/prevent_MS_runtime_libs_being_installed_again.patch  # [win]

build:
  number: 0
  skip: True  # [win and vc<14]
  run_exports:
    #   https://abi-laboratory.pro/tracker/timeline/netcdf/
    - {{ pin_subpackage('libnetcdf') }}

requirements:
  build:
    - cmake
    - make  # [not win]
    - pkg-config  # [not win]
    - {{ compiler('c') }}
  host:
    - msinttypes  # [win and vc<14]
    - bzip2
    - curl
    - zlib
    - hdf4
    - hdf5
    - jpeg
  run:
    - bzip2
    - curl
    - zlib
    - hdf4
    - hdf5
    - jpeg
    # Curl should be pulling this... Investigate it later.
    - libssh2  # [win]

test:
  commands:
    - test -f ${PREFIX}/lib/libnetcdf.a  # [not win]
    - test -f ${PREFIX}/lib/libnetcdf${SHLIB_EXT}  # [not win]
    - nc-config --all  # [not win]
    # All these endpotins failed at some point due to various reasons.
    #- ncdump -h "http://geoport-dev.whoi.edu/thredds/dodsC/estofs/atlantic"
    #- ncdump -h "https://data.nodc.noaa.gov/thredds/dodsC/ioos/sccoos/scripps_pier/scripps_pier-2016.nc"
    #- ncdump -h "http://oos.soest.hawaii.edu/thredds/dodsC/hioos/model/atm/ncep_pac/NCEP_Pacific_Atmospheric_Model_best.ncd"
    #- ncdump -h "http://oos.soest.hawaii.edu/thredds/dodsC/usgs_dem_10m_tinian"
    #- ncdump -h "https://www.ncei.noaa.gov/thredds/dodsC/namanl/201609/20160929/namanl_218_20160929_1800_006.grb"

about:
  home: http://www.unidata.ucar.edu/software/netcdf/
  license: MIT
  license_file: COPYRIGHT
  summary: 'Libraries and data formats that support array-oriented scientific data'

extra:
  recipe-maintainers:
    - groutr
    - kmuehlbauer
    - ocefpaf
    - mingwandroid
    - msarahan
    - beckermr
