appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Nx8IpDAhzL7IVDEQVjcFhKVH6LKxvhEZm0fBUI6naCi+H41Byd/EBqaGwJkYmY+Nuy3xeGh3778DpWdmyPcs3FR6i/LQ3dJV26sJDvGLDYM2DTgy42IUwA47z1vaHjGJdYbt2mKwHYmR8TOmO0Luwb2K3AFJ3y0XLWMXX8CZRFOtOjtRtsEIOARWtYdeepQB6TCaedD9hqbwYSY3+enAYkGYVvurvJNQGe37E7oIuS07XR+JyieoYpP6/SX1gF3P5LdDolANeoDtTTNXvElkpZRbpXDoYU7wzUzFFwc8RLe4pLIKhaD0uS55zeEnFt3SJpO/deK5SdIMITzNSe9aUE53lBFNZ6DHcXHvSVlQN4Vxq23iT7wyNLjUOvtaPiWpIt5UebWSDsQjQhwoNGLell5R8QOimlPtjiC8g7mLgatbsh4wIscsY/Pbk/Jc76hz0tndOfR3LJw8xZLBW8WTKikX6jTS9ECJLYduu2r9SEkqCPyCNHNlv2kc4lmfca4WW7dxIMXslmCJRoT0iGVCGKmeJz5xLNtrFzKdOIXtMnVxAhhFCWLXM7nlU8nVYNjMLAPDRBGA//bLqgosElHZo3tiwd02JXB4HZkTWF6tADtxBCPgT1R+xxqQ6yBVB4sVYEfY5p76VPybO3vGYFlxmJA1piV3xVBzv3/jsAbLoDc=}
